title: "FLAIR IISC"
author: "Danish Pruthi"
description: "Our group broadly works in the areas of Natural Language Processing (NLP). Our research focuses on developing robust, fair, and interpretable AI systems."
email: "danish@iisc.ac.in"
twitter_username: "danish037"
github_username: "flair-iisc"

theme: "jekyll-theme-dinky"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

nav:
  - name: "Blog"
    link: /blog/
  - name: "Archive"
    link: /archive/