title: "Let's Talk Tokens"
author: "Danish Pruthi"
description: "We are FLAIR Lab, part of the Department of Computational and Data Sciences at the Indian Institute of Science. Our research lies at the intersection of Natural Language Processing (NLP) and responsible AI, with a focus on building systems that are robust, fair, and interpretable. Through this blog, we share our perspectives on recent advances in NLP, highlight our own research, and reflect on broader questions and curiosities in the field."
email: "danish@iisc.ac.in"
twitter_username: "danish037"
github_username: "flair-iisc"
repository: "dayitachaudhuri/jekyll-blog"

# theme: "jekyll-theme-dinky"

# theme: "jekyll-theme-dinky"
# theme: "jekyll-theme-slate"
# theme: "jekyll-theme-cayman"
# theme: "jekyll-theme-hacker" #DARK
theme: "jekyll-theme-leap-day" # Preferred
# theme: "jekyll-theme-merlot" # Shiny
# theme: "jekyll-theme-midnight" # DARK
# theme: "jekyll-theme-minimal"
# theme: "jekyll-theme-modernist" # Good
# theme: "jekyll-theme-tactile" # decent
# theme: "jekyll-theme-time-machine" # too shiny

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

nav:
  - name: "Blog"
    link: /
  - name: "Archive"
    link: /archive/